config/routes.rb
Rails.application.routes.draw do
  
  devise_for :admin_users, ActiveAdmin::Devise.config

  get 'opinions/index'

  get 'gallaries/index'

  get 'menus/index'

  get 'home/index'

  get 'admin/index' => 'admin#index'

  resources :home
  resources :menus
  resources :gallaries
  resources :opinions
  root 'home#index'

  ActiveAdmin.routes(self)
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :name
  has_many :menus
end

app/models/gallary.rb
class Gallary < ActiveRecord::Base
end

app/models/menu.rb
class Menu < ActiveRecord::Base
  attr_accessible :title,:category_id,:body,:rate

  belongs_to :category
end

app/models/opinion.rb
class Opinion < ActiveRecord::Base

  attr_accessible :name, :email, :q1, :q2, :q3, :q4,:improvement,:created_at
  validates :name, presence: true
  validates :email, presence: true
  validates :q1, presence: true
  validates :q2, presence: true
  validates :q3, presence: true
  validates :q4, presence: true
  validates :improvement, presence: true

end

app/models/special.rb
class Special < ActiveRecord::Base
  attr_accessible :title, :body

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :all_feedback
  helper_method :all_special

  def all_feedback
    @name = Opinion.all
  end

  def all_special
    @spe = Special.all;
  end
end

app/controllers/gallaries_controller.rb
class GallariesController < ApplicationController
  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

  end

  def contact

  end
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
  def index
    @menu = Menu.all
    @category = Category.all
    @category_first = Category.first
  end
end

app/controllers/opinions_controller.rb
class OpinionsController < ApplicationController
  def index
    @opn = Opinion.new
  end
  def new

  end

  def create

    @opinion = Opinion.new(params[:opinion])
    if @opinion.save
      redirect_to opinions_index_path , :notice => "Thank you for your valuable feedback"
    else
      redirect_to opinions_index_path
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/gallaries/index.html.erb
<div class="main-body">
  <div class="grids">
    <div class="gallery">
      <ul>
        <li><%= image_tag "g1.jpg"%></li>
        <li><%= image_tag "g2.jpg"%></li>
        <li><%= image_tag "g3.jpg"%></li>
        <li><%= image_tag "g4.jpg"%></li>
        <li><%= image_tag "g5.jpg"%></li>
        <li><%= image_tag "g6.jpg"%></li>
        <li><%= image_tag "g7.jpg"%></li>
        <li><%= image_tag "g8.jpg"%></li>
        <li><%= image_tag "g9.jpg"%></li>
        <li><%= image_tag "g10.jpg"%></li>
        <li><%= image_tag "g11.jpg"%></li>
        <li><%= image_tag "g12.jpg"%></li>
        <li><%= image_tag "g13.jpg"%></li>
        <li><%= image_tag "g14.jpg"%></li>
        <li><%= image_tag "g1.jpg"%></li>
        <div class="clear"></div></ul>
    </div>

    <div class="clear"> </div>
  </div>
  <div class="clear"> </div>
</div>

app/views/home/_footer.html.erb
<div class="footer1">

    <div class = "footer_time">
      <p>Mon - Sat 9:00 AM to 10:00 PM</p>
      <p>closed on sunday. 409-832-6386</p>

    </div>
    <div class = "footer_add">
      <p>4637 Rolfe Christopher Dr</p>
      <p>Beaumont, TX 77705 </p>
    </div>
  <div class="footer-grid2">
    <ul>
      <li><a href="https://www.facebook.com/pages/Kampus-Korner-Bar-Grill/217331568294921"><%= image_tag "facebook.png" %></a></li>
      <li><a href=""><%= image_tag "twitter.png"%></a></li>
      <li><a href=""><%= image_tag "rss.png"%></a></li>
    </ul>
  </div>
  <div class="clear"> </div>
</div>

app/views/home/_header.html.erb
<div class="header">
  <div class="logo"><a href="index.html"></a><%= image_tag "logo1.png" %></div>
  <div class="search">
    <!--<form>-->
    <!--<input type="text" value="" />-->
    <!--<input type="submit" value="" />-->
    <!--</form>-->
  </div>
  <div class="clear"> </div>
</div>
<div class="nav">
  <ul>
    <li ><%=link_to "Home" , home_index_path %></li>
    <li><%=link_to "Gallery" , gallaries_path %></li>
    <li><%=link_to "Menu" , menus_index_path %></li>
    <li><%=link_to "Contact" , opinions_index_path %></li>
    <div class="clear"> </div>
  </ul>
</div>

app/views/home/_sidebar.html.erb
<script type="text/javascript">

    $(function(){
        $('#_sidebar').slimScroll({
            height: "400px"
        })
    });

</script>
<div class="boxes">
  <div >
    <ul>
      <li style="width: 100%"><a target="_blank" href="http://kampuskornerlamar.com/">
        <%= image_tag "order_now.png"%>
      </a> </li>
    </ul>
  </div>
  <div class="clear"> </div>
  <p style="
  background: none;
          font-size: medium;
          font-family: cursive;
          font-style: italic;
          color: floralwhite;
  ">What people says about us!</p>
  <div id= "_sidebar" style="  overflow-x: hidden;">
    <% all_feedback.each do |option| %>
        <div class="feedbackFromUser">
          <div id= "_feedback" style="height: 73%;width: 95%;overflow: hidden" >
            <p style="padding-bottom: 2%">
              <span ><%= option.name %></span>
            </p>
            <p><%= option.improvement %></p>
          </div>
        </div>
    <% end %>
  </div>
</div>

app/views/home/index.html.erb
<div class="main-body">
  <div id="slider">
    <a href="#" target="_blank">
      <%= image_tag "slider-1.jpg"%>

    </a>
    <a href="#" target="_blank">
      <%= image_tag "slider-2.jpg"%>

    </a>
    <a href="#" target="_blank">
      <%= image_tag "slider-3.jpg"%>

    </a>
  </div>
  <div class="clear"> </div>
  <div >
    <ul>
      <li style="width: 50%;float: right"><a target="_blank" href="http://kampuskornerlamar.com/">
        <%= image_tag "order_now.png"%>
      </a> </li>
    </ul>
  </div>
  <div class="home_content">
    <div style="font-size: xx-large;
            padding-bottom: 3%;">
      <p >
        Welcome to Kampus Korner Restaurant!</p>
      <p style="
      text-align: center;
              color: floralwhite;
              font-size: x-large;
      "> <% all_special.each do |spe| %>
            <%= spe.title%>
        <%end %></p>


    </div>
    <p style="font-size: initial; padding-bottom: 2%">
      Located in the hub of  Lamar University, you will feel right at home with the different seating areas and the comfortable couches, grouped for gatherings with friends.
      Kampus provides a pleasant place  to eat, study, or just take a deep breath and relax. But the Korner is not just for collegians.
      Equally at home are Lamar employees stopping in for breakfast and refinery workers seeking the refuge of a cold beer after a long, hot day.
    </p>
    <p style="font-size: initial;">
      Breakfast starts at 9 a.m.
      featuring the perfect omelet or eggs cooked just the way you like them with all the trimmings.
      The pancakes are very popular. The breakfast sandwiches are filling and offer lots of protein and carbs before you hit the gym.
      Kampus Korner has great coffee and plent of it if you are cramming for an exam.
    </p>
  </div>

  <div class="clear"> </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>KampuskornerMobile</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'defaults', 'data-turbolinks-track' => true %>

  <%= csrf_meta_tags %>


  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <%= stylesheet_link_tag 'style' %>
  <%= stylesheet_link_tag 'slider-styles' %>
  <%= javascript_include_tag 'jquery.js' %>
  <%= javascript_include_tag 'slider' %>
  <%= javascript_include_tag 'jquery-ui.min' %>
  <%= javascript_include_tag 'jquery.slimscroll.min' %>

  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  <script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
  <meta name="keywords" content="Food-Point Iphone web template, Andriod web template, Smartphone web template, free webdesigns for Nokia, Samsung, LG, SonyErricsson, Motorola web design" />

</head>
<body>

<!--<div class="body_header" >-->
  <!--<div class="top-head">-->
    <!--<div class="welcome">Welcome To <span>Kampus Korner</span></div>-->
    <!--<div class="clear"> </div>-->
  <!--</div>-->
<!--</div>-->

<div class="body_main">
  <div class="wrap">
    <%= render 'home/header' %>
    <%= yield %>
  </div>

<%= render 'home/footer'%>


<script>
    $('#slider').coinslider();
</script>

</div>
</body>
</html>

app/views/menus/index.html.erb
<div class="main-body">
  <% @category.each do |x| %>

      <div id="cat_<%= x.id%>" style="
      text-align: center;
              background-color: brown;
              font-family: cursive;
              font-size: x-large;
              color: khaki;cursor: pointer;
      ">
        <%= x.name%>
      </div>
      <div id="menu_<%= x.id%>" style="
              font-family: cursive;
              font-size: medium;
      ">
        <% @menu.where("category_id"=> x.id).each do |y| %>
            <p style="height: 30px; background-color: bisque"><span style="float: left; width: 80%"><%=y.title %></span><span style="float:
                    right">$<%= y.rate%></h2></span></p>
        <%end%>
      </div>

  <% end%>

  <div class="clear"> </div>
</div>

<script type="text/javascript">
    $(document).ready(function() {
        <% @category.each do |x| %>
        $("#cat_<%=x.id%>").click(function () {
            $("#menu_<%=x.id%>").toggle("normal");
        });
        $("#menu_<%=x.id%>").toggle();
        <%end%>

    });
</script>

app/views/opinions/index.html.erb
<div class="main-body">
  <div>
   <a target="_blank" href="https://www.google.com/maps/place/Kampus+Korner+Restaurant/@30.0413162,-94.0728179,17z/data=!3m1!4b1!4m2!3m1!1s0x863eca79086ceeab:0x704b6f5fad49fe5c"> <%=image_tag "locatin.png" %></a>
    </div>
  <br />
  <div style="font-family: cursive;font-size: small;color: khaki">
    <p style="font-size: large;">Working hours</p>
    <p>Monday - Saturday 9:00 AM to 10:00 PM</p>
    <p>closed on sunday</p>
    <p style="font-size: large; padding-top: 2%">Contaact us</p>
    <p>4637 Rolfe Christopher Dr</p>
    <p>Beaumont, TX 77705</p>
    <p>phone: 409-832-6386</p>
  </div>
  <div class="clear"> </div>
</div>